version: '3'

services:
  devops-mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=timesheet-devops-db
    ports:
      - "3308:3306"
  devopsimage:
    image: tarekbenyahia/devopsimage
    depends_on:
      - devops-mysql
    ports:
      - "8082:8082"
    links:
      - devops-mysql
    environment:
       spring.datasource.url: jdbc:mysql://devops-mysql:3306/timesheet-devops-db?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
       spring.datasource.username: root
       spring.datasource.password:
    build:
      context: "./"
      dockerfile: Dockerfile
